In [1]:
import pandas as pd
import numpy as np
import matplotlib.pylab as plt
import seaborn as sn
plt.style.use('ggplot')
pd.set_option('display.max_columns', 200)
from sklearn import linear_model

In [2]:
df = pd.read_csv('/kaggle/input/multivariable-practice/homeprices.csv')

In [3]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [5]:
df['bedrooms'].median()

4.0

In [6]:
# Fill missing values

df['bedrooms'] = df['bedrooms'].fillna(df['bedrooms'].median())

In [7]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [10]:
reg = linear_model.LinearRegression()
reg.fit(df[['area','bedrooms','age']],df['price'])

LinearRegression()

In [11]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [12]:
reg.intercept_

221323.00186540396

In [13]:
# Find price of home with 3000 sqr ft area, 3 bedrooms, 40 year old

reg.predict([[3000, 3, 40]])

/opt/conda/lib/python3.10/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([498408.25158031])

In [15]:
# Find price of home with 2500 sqr ft area, 4 bedrooms, 5 year old

reg.predict([[2500, 4, 5]])

/opt/conda/lib/python3.10/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([578876.03748933])