In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
import matplotlib.pyplot as plt
digits = load_digits()

In [2]:
dir(digits)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data,digits.target,test_size=0.3)

# Logistic Regression

In [15]:
lr = LogisticRegression(solver='liblinear',multi_class='ovr')
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.9611111111111111

# SVM

In [14]:
svm = SVC(gamma='auto')
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.3111111111111111

# Random Forest

In [13]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9629629629629629

# KFold cross validation

In [16]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [17]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [21]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train,y_train)
    return model.score(X_test, y_test)

In [23]:
get_score(LogisticRegression(solver='liblinear',multi_class='ovr'), X_train, X_test, y_train, y_test)

0.9611111111111111

In [25]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

In [27]:
scores_logistic = []
scores_svm = []
scores_rf = []

for train_index, test_index in kf.split(digits.data):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
                                        digits.target[train_index], digits.target[test_index]
    scores_logistic.append(get_score(LogisticRegression(solver='liblinear',multi_class='ovr'), X_train, X_test, y_train, y_test))  
    scores_svm.append(get_score(SVC(gamma='auto'), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))

In [28]:
scores_logistic

[0.8964941569282137, 0.9515859766277128, 0.9115191986644408]

In [29]:
scores_svm

[0.41068447412353926, 0.41569282136894825, 0.4273789649415693]

In [30]:
scores_rf

[0.9298831385642737, 0.9565943238731218, 0.9315525876460768]

# Cross value function

In [31]:
from sklearn.model_selection import cross_val_score

In [32]:
cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'), digits.data, digits.target,cv=3)

array([0.89482471, 0.95325543, 0.90984975])

In [33]:
cross_val_score(SVC(gamma='auto'), digits.data, digits.target,cv=3)

array([0.38063439, 0.41068447, 0.51252087])

In [34]:
cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target,cv=3)

array([0.92153589, 0.93656093, 0.92320534])

# Parameter tuning

In [35]:
cross_val_score(RandomForestClassifier(n_estimators=10),digits.data, digits.target,cv=3)

array([0.87646077, 0.92487479, 0.9015025 ])

In [36]:
cross_val_score(RandomForestClassifier(n_estimators=20),digits.data, digits.target,cv=3)

array([0.92320534, 0.93989983, 0.92153589])

In [37]:
cross_val_score(RandomForestClassifier(n_estimators=30),digits.data, digits.target,cv=3)

array([0.91986644, 0.93989983, 0.92487479])

In [38]:
cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target,cv=3)

array([0.93155259, 0.95158598, 0.92988314])

In [39]:
cross_val_score(RandomForestClassifier(n_estimators=50),digits.data, digits.target,cv=3)

array([0.94323873, 0.95158598, 0.91652755])